### ISSUE TITLE
Players after TestPlayer do not have correct graph

### ISSUE THREAD

**Issue by erikkut** [osveliz/cardpickup#1]
Only the first player initialized seems to get the correct graph. The rest get nodes with only one possible card despite the game arguments.

**Comment by osveliz** [comment]
Can I see the output you are getting? Perhaps the code you are using?

**Comment by osveliz** [comment]
Below is a original graph:
1,4,6
0,3,9
6,7,10
1,8,10
0,5,11
4,8,11
0,2,7
2,6,9
3,5,9
1,7,8
2,3,11
4,5,10
Seven of Clubs
Seven of Hearts
Nine of Diamonds
Ten of Hearts
Jack of Clubs
Ten of Spades
Six of Clubs
King of Clubs
Two of Diamonds
Eight of Diamonds
Five of Clubs
Queen of Hearts


This is the obfuscated version
1,4,6
0,3,9
6,7,10
1,8,10
0,5,11
4,8,11
0,2,7
2,6,9
3,5,9
1,7,8
2,3,11
4,5,10
Four of Spades,Seven of Clubs,Nine of Spades,Queen of Clubs
Five of Hearts,Three of Spades,Jack of Hearts,Seven of Hearts
Two of Diamonds,Nine of Diamonds,Queen of Diamonds,Ten of Spades
Six of Hearts,Ten of Hearts,Two of Spades,Three of Clubs
Ace of Diamonds,Jack of Clubs,Ten of Spades,Queen of Clubs
Ten of Diamonds,Ten of Spades,Eight of Diamonds,Six of Clubs
Four of Clubs,Jack of Diamonds,Six of Clubs,Jack of Hearts
King of Clubs,Ace of Spades,Queen of Spades,Three of Hearts
King of Clubs,Queen of Hearts,Two of Diamonds,Jack of Diamonds
Eight of Diamonds,Six of Hearts,Queen of Diamonds,Four of Hearts
Six of Clubs,Five of Clubs,Five of Spades,Jack of Clubs
Five of Hearts,Five of Diamonds,King of Diamonds,Queen of Hearts

**Comment by osveliz** [comment]
Thank you for providing the fix. I will close this issue.
